title: City of Amsterdam development standard

include: [CONTRIBUTING.md]
permalink: pretty

# Settings for the Amsterdam Jekyll Theme
remote_theme: amsterdam/amsterdam-jekyll-theme
headerHideLogo: true
toc: true
